spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    jdbc:
      initialize-schema: never   # 禁止quartz自动建表
    job-store-type: jdbc